# Generated by Django 4.1.5 on 2023-01-05 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('user_email', models.EmailField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Почта')),
                ('user_phone', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')], verbose_name='Телефон')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
    ]
